import { Inter } from 'next/font/google';
import RootLayout from './RootLayout';
import './globals.css';
import { Providers } from './Providers';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'XCARD',
  description: 'Generated by Next.js',
};

const ServerLayout = ({ children }: { children: React.ReactNode }) => {
  const themeCookie = cookies().get('theme')?.value || 'Auto';

  let themeClass = '';
  if (themeCookie === 'Dark') {
    themeClass = 'dark';
  } else if (themeCookie === 'Light') {
    themeClass = 'light';
  } else {
    themeClass = '';
  }

  return (
    <html lang="en" className={themeClass}>
      <head>
      <script id="set-theme" dangerouslySetInnerHTML={{
        __html: `
          (function() {
            const savedSettings = localStorage.getItem('interfaceSettings');
            const settings = savedSettings ? JSON.parse(savedSettings) : { theme: 'Auto' };
            const theme = settings.theme;
            const root = document.documentElement;

            if (theme === 'Dark') {
              root.classList.add('dark');
            } else if (theme === 'Light') {
              root.classList.add('light');
            } else {
              const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
              root.classList.add(prefersDark ? 'dark' : 'light');
            }
          })();
        `
      }} />
      </head>
      <body className={inter.className}>
        <Providers>
          <RootLayout>{children}</RootLayout>
        </Providers>
      </body>
    </html>
  );
};

export default ServerLayout;